valgrind-test: Only check for 'FAIL' in glean tests.

diff --git a/tests/valgrind-test/valgrind-test b/tests/valgrind-test/valgrind-test
--- a/tests/valgrind-test/valgrind-test
+++ b/tests/valgrind-test/valgrind-test
@@ -23,9 +23,11 @@ if echo "$output" | grep -q '^PIGLIT.*pass'; then
 fi
 
 # Report a valgrind error for glean tests without any failures.
-if echo "$output" | grep -qv 'FAIL'; then
-   echo "PIGLIT: {'result': 'fail' }"
-   exit 1
+if echo "$@" | grep -q 'glean'; then
+    if echo "$output" | grep -qv 'FAIL'; then
+        echo "PIGLIT: {'result': 'fail' }"
+        exit 1
+    fi
 fi
 
 # Otherwise, the underlying test failed, so we simply report a piglit
